# Generated by Django 2.1.7 on 2019-08-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion_Libro',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('ibn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Autor',
            fields=[
                ('id_libro_autor', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=None)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoobReads.Autor')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoobReads.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=40)),
                ('nacimiento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='calificacion_libro',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoobReads.Libro'),
        ),
        migrations.AddField(
            model_name='calificacion_libro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoobReads.Usuario'),
        ),
    ]
