# Generated by Django 2.1.7 on 2019-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoobReads', '0002_auto_20190819_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro_autor',
            name='calificacion',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.CharField(max_length=10),
        ),
    ]
