# Generated by Django 2.2.3 on 2019-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoobReads', '0003_auto_20190819_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='clave', max_length=40),
        ),
    ]
