# Generated by Django 2.2.3 on 2019-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoobReads', '0004_usuario_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=40),
        ),
    ]
