# Generated by Django 2.2.3 on 2019-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoobReads', '0008_autor_calificacion_libro_libro_autor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.CharField(max_length=500),
        ),
    ]
