# Generated by Django 2.2.3 on 2019-08-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoobReads', '0009_auto_20190824_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id_libro',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='libro_autor',
            name='id_autor',
        ),
        migrations.RemoveField(
            model_name='libro_autor',
            name='id_libro',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Libro_Autor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
